title: candy coated violence
author: Some Luvie
email: getwellsoonwendy@rv.com
description: > # this means to ignore newlines until "baseurl:"
 This is a site to discuss South Korea's irreplaceable girl group, Red Velvet.
# social links
twitter_username: @RVsmtown
github_username:  agfran

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
